feat: code checker using golang-lint ci

diff --git a/.github/workflows/go.yml b/.github/workflows/go.yml
--- a/.github/workflows/go.yml
+++ b/.github/workflows/go.yml
@@ -1,21 +1,17 @@
 name: Go
 on: [push]
 jobs:
-
   build:
     name: Build
-    runs-on: ubuntu-latest
+    runs-on: ubuntu-20.04
     steps:
-
     - name: Set up Go 1.17
       uses: actions/setup-go@v1
       with:
         go-version: 1.17
       id: go
-
     - name: Check out code into the Go module directory
       uses: actions/checkout@v1
-
     - name: Get dependencies
       run: |
         go get -v -t -d ./...
@@ -25,3 +21,63 @@ jobs:
         fi
     - name: Build
       run: go build -v ./...
+  
+  analyze-codeql:
+    name: "code-analysis-codeql"
+    runs-on: ubuntu-20.04
+    needs: [build]
+    permissions:
+      actions: read
+      contents: read
+      security-events: write
+    strategy:
+      fail-fast: false
+      matrix:
+        language: [ 'go' ]
+    steps:
+    - name: Checkout code
+      uses: actions/checkout@v1
+    - name: Initialize CodeQL
+      uses: github/codeql-action/init@v2
+    - name: Autobuild
+      uses: github/codeql-action/autobuild@v2    
+    - name: Perform CodeQL Analysis
+      uses: github/codeql-action/analyze@v2
+
+
+  analyze-go-linters:
+    name: "code-analysis-go-linters"
+    runs-on: ubuntu-20.04
+    needs: [build]
+    steps:
+      - name: Set up Go 1.17
+        uses: actions/setup-go@v1
+        with:
+          go-version: 1.17
+        id: go
+      - name: Check out code into the Go module directory
+        uses: actions/checkout@v1
+
+      - name: Get dependencies
+        run: |
+          go get -v -t -d ./...
+          if [ -f Gopkg.toml ]; then
+              curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
+              dep ensure
+          fi
+
+      - name: "go-vet"
+        run: |
+          go vet ./...
+          if [ "$?" != "0" ]; then
+              echo "Go vet failed"
+              exit 1
+          fi
+
+      - name: golangci-lint
+        uses: golangci/golangci-lint-action@v3
+        with:
+          version: v1.29
+          working-directory: .
+          args: --enable-all -D errcheck,varnamelen
+          only-new-issues: true
